service: tool-slack-select-list

provider:
  name: aws
  runtime: nodejs12.x

functions:
  search:
    memorySize: 128
    handler: handler.search
    events:
      - http: 
          path: search
          method: post
